spring:
  application:
    name: webStoreApp
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: pass
  jpa:
    hibernate:
      ddl-auto: update #validate, create, update, none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    change-log: changeLogs/changeLog.yml
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: webApp
      auto-offset-reset: earliest
      properties:
        spring.json.trusted.packages: '*'

server:
  port: 8080