CREATE SCHEMA IF NOT EXISTS mainSchema;

CREATE SEQUENCE IF NOT EXISTS mainschema.products_id_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE IF NOT EXISTS mainschema.cart_id_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE IF NOT EXISTS mainschema.users_id_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE IF NOT EXISTS mainschema.discounts_id_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE IF NOT EXISTS mainschema.levelsOfLoyalty_id_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE IF NOT EXISTS mainschema.roles_id_seq START WITH 1 INCREMENT BY 1;